access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
spring:
  data:
    mongodb:
      uri: mongodb+srv://lalindum99:7812833@foodiesss.tanopz1.mongodb.net/?retryWrites=true&w=majority
logging:
  level:
    org.springframework.security: DEBUG